version: '2.0'
services:
  mng:
    build: .
    entrypoint:
    - /sbin/my_init
    - --skip-runit
    - --skip-startup-files
    - --
    command:
    - /DOCKAPP/run.sh
    environment:
      CFG_DIR: /DOCKAPP
    image: malex984/dockapp:mng
    labels:
     - "is_top_app=1"
     - "description=Management front-end and back-end"
    ports:
     - "8081:8080"
    privileged: false
    restart: on-failure:5
    stdin_open: false
    tty: false
    working_dir: /DOCKAPP
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /tmp:/tmp:rw
    - "${PWD}:/DOCKAPP:rw" 
    - "${HOME}/.ssh:/root/.ssh:ro"  
    - "${HOME}:${HOME}:ro" 
    - "${PWD}/dockapp_dashboard:/usr/local/dockapp_dashboard:ro"
